### ISSUE TITLE
SaveManager Couldn't find name

### ISSUE THREAD

**Issue by Moltak1** [grifkuba/sota-issues#24]
**Describe the bug**
SaveManager loading cannot find name entry.
SaveManager save_data is deleting the name entry when slot is empty due to null value.

**SaveManager.gd**
```
for slot in _G.game_data:
		config.set_value(slot, "newgame", false)
		config.set_value(slot, "name", _G.game_data[slot].name)
		config.set_value(slot, "data", _G.game_data[slot].data)
	config.save("user://save.dat")
```

**Globals.gd ( _G)**
```
var game_data = {
	"1" : {
		"newgame" : true,
		"name" : null,
                ...

```

**Godot documentation**
```
void set_value(section: String, key: String, value: Variant)

Assigns a value to the specified key of the specified section.
If either the section or the key do not exist, they are created. 
Passing a null value deletes the specified key if it exists, and deletes the section if it ends up empty once the key has been removed.

```
**To  #Reproduce**
Code error no steps

**Expected behavior**
name entry should be saved not deleted

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**

**Comment by Moltak1** [comment]
This probably affects more than just the name entry on the save file since everything has a default value of null I also need this solved to do #22

**Comment by Sudospective** [comment]
I don't understand this issue. Is this something that is hindering progress in the game? If so, I haven't been able to see that in my own tests. Otherwise, I'm not sure what to do about this. The point of how the load and save functions work is that things are supposed to return null if we don't have save data for them. For instance, if we have save data in slots 1 and 2, and not in slot 3, we are supposed to be returning null for slot 3's name and data, so that the rest of the code knows what to do from there.

**Comment by Sudospective** [comment]
#22 has been closed, this seems no longer an issue. Submit a new issue if problems arise again.
