### ISSUE TITLE
The battle just stopped in the middle of me attacking

### ISSUE THREAD

**Issue by Sudospective** [grifkuba/sota-issues#27]
**Location of bug:**
Jungle Planet
**Stack trace:**
**Additional info:**
The battle just stopped in the middle of me attacking.

**Comment by tacopill** [comment]
**Describe the bug**
The battle just stopped in the middle of me attacking

**To Reproduce**
Steps to reproduce the behavior:
1. Be in a battle
2. Navigate through the battle until you come up to a point where the battle fails to give the menu options again

**Expected behavior**
The battle to continue on schedule.

**Screenshots**
If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/50280385/116297613-71f1aa80-a769-11eb-9002-f6f50eb453ff.png)

Desktop (please complete the following information):

- OS: Windows 10
- Browser N/A
- Version N/A

Smartphone (please complete the following information):

- Device: N/A
- OS: N/A
- Browser N/A
- Version N/A

**Additional context**
Add any other context about the problem here.

**Please attach `log.txt` to your bug report for faster assistance** (located in C:\Users\{username}\AppData\Roaming\Godot\app_userdata\Seekers-of-the-Aether)

[log.txt](https://github.com/grifkuba/sota-issues/files/6386980/log.txt)

The file was in

C:\Users\tacopill\AppData\Roaming\Godot\app_userdata\SotA GitHub

**Comment by Moltak1** [comment]
**Describe the bug**
If you cancel an attack after selecting to attack the attack gets queued without a target.

**To Reproduce**
Steps to reproduce the behavior:

    1.Be in a battle
    2.Select Attack > Fight > Cancel
    3. End turn until battle
    4. game will crash


**Expected behavior**
Attack action shouldn't be added without a valid target.

**Comment by Moltak1** [comment]
After more testing the more common cause is that you can Initiate an attack without enough motions left causing the same problem.

**Comment by Sudospective** [comment]
Sounds like we just need a motion check for the fight button.

**Comment by Clover10123** [comment]
Can we close this?

**Comment by Moltak1** [comment]
Yes please close this, I can't

**Comment by Moltak1** [comment]
Yes please close this, I can't
